CREATE TABLE IF NOT EXISTS users(
   id INT (11) AUTO_INCREMENT NOT NULL,
   fullname VARCHAR (255) UNIQUE NOT NULL,
   email VARCHAR (255) UNIQUE NOT NULL,
   password VARCHAR (255) NOT NULL,
   active TINYINT,
   createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updatedAt TIMESTAMP NOT NULL,
   PRIMARY KEY(id)
);
