version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/go/src
    tty: true
    ports:
      - 8081:8080
    command: /bin/sh
    networks:
      - restapi_network
  ### ===================
  ### SWAGGER SERVICE
  ### ===================
  doc:
    build:
      context: .
      dockerfile: swagger/Dockerfile
    restart: always
    volumes:
      - ./swagger/openapi.yml:/usr/share/nginx/html/openapi.yml
    healthcheck:
      interval: 120ms
      retries: 5
      start_period: 60ms
      test: |
        touch /tmp/healthcheck.txt &&
        mkdir /tmp/healthcheck &&
        mv /tmp/healthcheck.txt /tmp/healthcheck &&
        cd /tmp/healthcheck &&
        echo "hello my docker container is working fine" >> healthcheck.txt &&
        cat healthcheck.txt &&
        rm healthcheck.txt &&
        cd .. &&
        rmdir /tmp/healthcheck
        cls
      timeout: 60ms
    environment:
      - URL=http://localhost/openapi.yml
      - SWAGGER_JSON=swagger/openapi.yml
    ports:
      - 80:8080
    networks:
      - restapi_network
  ### ===================================
  ### NETWORKS GROUP FOR ONE SAME SERVICE
  ### ===================================
networks:
  restapi_network:
